---
- name: Enable other packages
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^# deb-src'
    line: "deb-src http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi"
  become: yes

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - htop
      - vim
      - git-core
    state: present
  become: yes

- name: Install docker
  pip:
    name: docker
  become: yes
